### ISSUE TITLE
SHIFT+TAB => get previous set

### ISSUE THREAD

**Issue by eecolella** [acejump/AceJump#179]
Hi,

I love the recent new feature:
```AceJump now searches the entire document. Press TAB to get the next set of search results!```

I think it would be nice also be able to go to the previous one.

Regards,

E.

**Comment by breandan** [comment]
Glad to hear you are enjoying the new <kbd>Tab</kbd> search feature, I was curious how it was being received. There was some noted frustration (cf. #161) due to the increased latency of searching large documents. This effect is slightly mitigated by recent changes to tag assignment ([some of which](https://github.com/johnlindquist/AceJump/issues/170) are yet to be released, that will decrease latency even further). I remain confident we can get the latency down for everyone, and am working to ensure the next release is more responsive.

We will try to push out <kbd>Shift</kbd>+<kbd>Tab</kbd> in the next few updates. This seemingly minor addition was originally scheduled to be released with the <kbd>Tab</kbd> search feature (the search code is [already implemented](https://github.com/johnlindquist/AceJump/blob/90957f43be193343387971031de68b653c23b8c1/src/main/kotlin/com/johnlindquist/acejump/search/Skipper.kt#L33), although binding <kbd>Shift</kbd> is complicated by the way we [handle keystrokes](https://github.com/johnlindquist/AceJump/blob/90957f43be193343387971031de68b653c23b8c1/src/main/kotlin/com/johnlindquist/acejump/control/Handler.kt#L78)), however this needed to be pushed back to gather feedback. In terms of latency, it should have no effect. Thank you for the feedback.
