### ISSUE TITLE
Feature request: "CamelHumps Mode" in addition to "Word Mode"

### ISSUE THREAD

**Issue by clojj** [acejump/AceJump#216]
it would be great to also have a camel-humps mode, i.e. jumping to a camel-hump directly
this depicts word-mode, but I often want to jump to a camel-hump for renaming purposes
![ace-camel-humps](https://user-images.githubusercontent.com/4367963/37247775-0ee47568-24c1-11e8-91d7-672390897a96.png)

**Comment by breandan** [comment]
Great suggestion! This is something I have been considering for a while, an [approximate](https://en.wikipedia.org/wiki/Approximate_string_matching) or [fuzzy search](https://stackoverflow.com/questions/2891514/algorithms-for-fuzzy-matching-strings) feature. Once we get a handle on the outstanding bugs, it would be a nice feature to tackle. Since we consider non-contiguous letters in words for tagging, it might conflict with the existing full-text search. We might need to introduce a new mode unless we can figure out how to assign tags to sites while allowing for collision-free expansion of non-adjacent but sequential search characters. It might be possible, but would probably reduce the number of available two-character tags.

**Comment by clojj** [comment]
Doesn't it just mean searching for upper/lowercase character sequences ?

**Comment by breandan** [comment]
If all you want is the ability to search for lower and upper case letters, then it currently supported in AceJump `3.5.1`. If you want to search for hump characters (`camelCaseSearch` -> `ccs`) a la IntelliJ IDEA's [camel case completion](https://www.jetbrains.com/help/idea/auto-completing-code.html#wildcards), then this is not yet supported.

**Comment by clojj** [comment]
Actually, I'd like to see this plugin know my Editor (General-)Setting "CamelHumps" and only select the camelHump **substring** when in Target Mode (the mode in which a word is _selected_ after the jump)

**Comment by breandan** [comment]
I was expecting the PR to be longer, but it's just as long as it needs to be! I wasn't aware of this `CamelHumps` setting, thanks for spotting.
