### ISSUE TITLE
Add option to place the caret after the search text

### ISSUE THREAD

**Issue by Exlll** [acejump/AceJump#225]
Could you please add an option or another shortcut to place the caret after the search text? I usally use AceJump to jump to a position and change/delete the specified symbol. It is a bit annoying having to type the arrow key every time.

**Comment by breandan** [comment]
To clarify, you want an option to will place the caret after the search text. For example:

```
...|queryresult = searchstring...
```

First you type <kbd>s</kbd>, then the tags appear:

```
...|queryKLsult KKsearKJstring...
```

Then you type <kbd>e</kbd><kbd>a</kbd><kbd>r</kbd><kbd>c</kbd>, which leads to:

```
...|queryresult =Ksearchstring...
```

then you type <kbd>k</kbd>, which leads to:

```
...queryresult = searc|hstring...
```

Is this interpretation correct? Just want to make sure I understand the proposed behavior.

**Comment by Exlll** [comment]
Yes, exactly!

**Comment by EeeMt** [comment]
hope this can be implemented

**Comment by vdakalov** [comment]
It could be implemented with pressing <kbd>Tab</kbd> for switch cursor to begin or end of all found match at the same time. And then you can press key of tag what do you want. This feature is really necessary and I hope it will implemented!

**Comment by tcqiuyu** [comment]
https://github.com/evandroforks/AceJump#jump-after-mode

acejump for sublime text has jump after mode. I think that is very useful and help someone can implement it.

**Comment by jornetsimon** [comment]
This is implemented in #347 and now shipped in [version 3.7](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735) 🥳

**Comment by tcqiuyu** [comment]
> This is implemented in #347 and now shipped in [version 3.7](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/115735) 🥳

@jornetsimon  I wondered how to activate jump to end mode in pycharm? I found for 10 mins but did not find the way😂

**Comment by jornetsimon** [comment]
> @jornetsimon I wondered how to activate jump to end mode in pycharm? I found for 10 mins but did not find the way😂

You can activate it either with a dedicated keyboard shortcut in your keymap (fig. 1), or by setting up modes cycle order as you wish in the AceJump config panel (fig. 2).
Just keep hitting the shortcut to cycle through the modes (the color of the caret will indicate which mode you are in).
<img width="1122" alt="Screen Shot 2021-04-11 at 22 57 44" src="https://user-images.githubusercontent.com/936101/114321108-5b1c4880-9b19-11eb-83f6-9aaa5b157a57.png">
<img width="1122" alt="Screen Shot 2021-04-11 at 22 46 23" src="https://user-images.githubusercontent.com/936101/114321136-78511700-9b19-11eb-8972-0a8a85f5d1e2.png">

**Comment by tcqiuyu** [comment]
Thanks. I found it is because I installed from pycharm extension marketplace, which is not v3.7. I installed from disk and everything works like charm. Bravo!

**Comment by StevenTammen** [comment]
I came across this issue when searching for how to use a separate hotkey to have the movement/selection be directly after the search text -- semantically representing "jump after search" (rather than the default behavior's "jump before search"). This is what is described in this reply from above:

> To clarify, you want an option to place the caret after the search text. For example:
> 
> ```
> ...|queryresult = searchstring...
> ```
> 
> First you type s, then the tags appear:
> 
> ```
> ...|queryKLsult KKsearKJstring...
> ```
> 
> Then you type earc, which leads to:
> 
> ```
> ...|queryresult =Ksearchstring...
> ```
> 
> then you select K, moving the caret to:
> 
> ```
> ...queryresult = searc|hstring...
> ```
> 
> Is this interpretation correct? Just want to make sure I understand the proposed behavior.

The feature added in #347 has the movement/selection extend to the end of the word. Unless I am missing something, this is not the same feature as the one initially requested. It is a related idea (and perhaps more useful in some or even many circumstances), but not the same thing.

Could this be re-opened for the original request to be implemented? I understand that very often we will be jumping to word-boundaries, but what if not? It just seems a bit less flexible to me. For example, what happens if you wish to jump to the end of the first-word in a CamelCase variable name? You could use the default jump behavior to jump before the "C" in Case, but what if you wanted to jump after the "l" in Camel?

I will say that part of my bias here is because I am accustomed in muscle memory (from a similar program in VSCode) to jump to characters rather than words. So my brain is wired already to jump to after the last character of a word rather than the first character of whatever comes after. And I see no reason why this ought not be an option too.

Thoughts?
