### ISSUE TITLE
Navigation to single symbol

### ISSUE THREAD

**Issue by Skorpionos** [acejump/AceJump#299]
For example I just want to move to the next symbol **"="** using AceJump. I need:
1. Press combination for activation AceJump mode;
2. Type **"="**
3. Press **"Enter"**
4. Press **"Esc"**
It's really difficult for this simple action. Is it a simpler way?
I would prefer to just press **Alt** + **"="**.
I propose to realize hot keys for actions:
a) go to next symbol 
b) go to previous symbol.

For example I assign **Alt** + **d** key for "go to next symbol action". Then I just press **Alt**+**d**+**"="**. Or I assign **Right Alt** for this action and I just press **Right Alt** + **"="**

**Comment by breandan** [comment]
@AlexPl292 has published a [new plugin](https://github.com/AlexPl292/IdeaVim-EasyMotion) called [EasyMotion](https://github.com/easymotion/vim-easymotion) which I believe supports the feature are describing. Can you please give it a try and let us know if it addresses your use case?

**Comment by AlexPl292** [comment]
IdeaVim-EasyMotion is currently available for EAP users of IdeaVim: https://youtrack.jetbrains.com/issue/VIM-820#focus=streamItem-27-3774944.0-0

**Comment by Skorpionos** [comment]
I'm sorry, but I didn't manage to understand how to configure and use **easymotion** plugin.

**Comment by Skorpionos** [comment]
@breandan, **IdeaVim-EasyMotion** is useful enough plugin, but not for this case. It also requires to press at least several keys, like: **<leader> + f + [char] + [label] or [Enter] and [Esc]**. In addition to this it requires navigation mode of vim.

**Comment by breandan** [comment]
I think the behavior you are describing is implemented by [Idea]Vim - to navigate to the next or previous instance of the word under the caret, you can press <kbd>*</kbd> or <kbd>#</kbd>. For a single-key jump, you may need to implement a [custom command](https://stackoverflow.com/questions/34285084/go-to-next-character-under-cursor-in-vim) in your `.ideavimrc`. Since AceJump is a modal tool, you will need to press *at least* three keys to jump from your current location to a new location: one to activate AceJump, one to tag and one to jump - shorter workflows may be possible, but are currently out of scope due to feature overlap with IdeaVim and vim-easymotion.
