### ISSUE TITLE
WebStorm: Unexpected behaviour when pressing Activate AceJump mode twice

### ISSUE THREAD

**Issue by avalanche1** [acejump/AceJump#301]
After pressing Activate AceJump mode twice and selecting a word - WebStorm opens Find usages dialog and starts searching for usages of selected word.
WebStorm v.2019.2.1
AceJump v.3.5.7

**Comment by tomsquest** [comment]
Related: pressing twice `ctrl+;` then a tag, goes to the specified tag but does not select the word and display the "cannot find declaration to go to" error popup. 
![image](https://user-images.githubusercontent.com/365778/65410673-4a976680-ddeb-11e9-8af6-e88a1d1f6320.png)

Versions:
- Acejump 3.5.7
- Intellij 2019.2.2
- Ubuntu 19.04

**Comment by breandan** [comment]
If you <kbd>Ctrl</kbd>+Left Click on the location in question, does it do anything? It appears the location is a string, so it may not have any declaration to visit. If not, AceJump’s declaration mode will have no effect.

**Comment by breandan** [comment]
@avalanche1 This is by design. Declaration mode will open the Find Usages dialog if the site in question is a definition/declaration. It is equivalent to pressing <kbd>Ctrl</kbd>/<kbd>⌘</kbd>+Click on the target word.

If you're looking for `Target Mode` feature, press the AceJump shortcut three times. As implemented, `Declaration Mode` works as intended, but perhaps we could improve the documentation, cf. #302

**Comment by tomsquest** [comment]
@breandan the documentation explains to press `ctrl+;` **two** times for target mode, am I wrong?

>Press the AceJump shortcut a second time before completing a tag to activate Target Mode. Once Target Mode is activated, jumping to a tag will select an entire word

I did see #302 and I can comment on this issue if you want.

**Comment by breandan** [comment]
Thanks for noticing, the README is indeed out of date in this aspect and should be updated. Let’s move discussion to that thread.
