### ISSUE TITLE
"Since" version should be updated

### ISSUE THREAD

**Issue by AlexPl292** [acejump/AceJump#309]
JBTextArea is available only since 183.  
`org.acejump.config.AceSettingsPanel#keyboardLayoutArea`

![image](https://user-images.githubusercontent.com/4203721/68404263-523e7f00-018f-11ea-9792-f1392b47f987.png)

**Comment by breandan** [comment]
A better solution might be to programmatically branch on the API version. The [SDK docs](https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html) do not have suggested pattern for handling API versioning, plugin authors must use the `since-build` or `until-build` attributes in the plugin manifest or otherwise maintain their own compatibility solution to support older IntelliJ Platform versions. In our case [`ApplicationInfo.getApiVersion()`](https://github.com/JetBrains/intellij-community/blob/7809c06ec20b5e3fab702d0e962175fb564f6c0a/platform/core-api/src/com/intellij/openapi/application/ApplicationInfo.java#L22) would probably do the trick, although it looks like the way [IDEA-201007](https://youtrack.jetbrains.com/issue/IDEA-201007) was [implemented](https://github.com/JetBrains/intellij-community/commit/89d0a64c8b0559edfd0dc1237befc0bf4c5455e0) this would still trigger an inspection error. cc: @serejke

I wonder if this would be better handled by a library similar to Android's [appcompat](https://developer.android.com/topic/libraries/support-library/packages) support library.

**Comment by serejke** [comment]
@breandan, by default this inspection takes `since-until` values from the `plugin.xml` but you may specify your own values in the inspection's settings (popup on the message -> right arrow -> Edit inspection profile settings).

I don't recommend doing it, though, as you might miss the same problem in other places.

API branching based on `ApplicationInfo.getApiVersion()` is not always possible: if a new API didn't have an alternative in previous IDE builds, you'd have to either promote "since" values or not implement the feature for older platforms.

It seems that the easiest option is to just declare "since" value to be <build used to compile your plugin>, so if it is, say, `183.6156.11` (corresponding to `2018.3.6`), then set the `since` to `183.6156.11`. Since the latest released IDE is 2019.2 and the 193 is on the way, there might be no need to support older platforms.
