### ISSUE TITLE
Jump position error

### ISSUE THREAD

**Issue by xianzheTM** [acejump/AceJump#328]
Use Ctrl+Shift+; ,did not jump correctly to the expected location
``` java
package work23;

/**
 * @author YLxia
 */
public class Age {
    public static void main(String[] args) {

    }

}

```
This is a screenshot.
![Snipaste_2020-04-27_12-36-04](https://user-images.githubusercontent.com/25103583/80334408-b3642700-8883-11ea-9fc1-f7fb8b3b0956.png)

I press the J and I.if correct，it should jump to line 12.But it jump to line 9.

 - OS: win10
 - IDEA 2020.1
 - AceJump 3.6.1

**Comment by yankolo** [comment]
I don't know if this is related, but I experience a similar issue. When I press Ctrl+;,→ and then try to type the corresponding hint letters, only the first letter is typed and the second one is not registered, which means that I can't jump to the end of the last line. For example, if the hint is "TT" and I type "TT", only "T" is registered which prevents the cursor to jump to the end of the last line (even if I type "T" multiple times, it still seems to be stuck). This only happens when I try to jump to the end of the last line.

Also, I don't if this is somehow related, but I noticed that when I press Ctrl+;,→, all the hints are single letters, but the last hint (the end of the last line) consists of two letters.

**Comment by xianzheTM** [comment]
> I don't know if this is related, but I experience a similar issue. When I press Ctrl+;,→ and then try to type the corresponding hint letters, only the first letter is typed and the second one is not registered, which means that I can't jump to the end of the last line. For example, if the hint is "TT" and I type "TT", only "T" is registered which prevents the cursor to jump to the end of the last line (even if I type "T" multiple times, it still seems to be stuck). This only happens when I try to jump to the end of the last line.
> 
> Also, I don't if this is somehow related, but I noticed that when I press Ctrl+;,→, all the hints are single letters, but the last hint (the end of the last line) consists of two letters.

**Comment by yankolo** [comment]
I don't think this issue should be closed. There is still a bug.

**Comment by breandan** [comment]
This is a valid issue and is related to #310. **Line mode** and **word mode** are known to have some edge cases producing unexpected jump destinations. Thank you for reporting.

**Comment by xianzheTM** [comment]
> I don't think this issue should be closed. There is still a bug.

It was my fault to close the problem (I was going to delete one of my comments), but another friend also said that the problem was related to #310, so I'll close it.

**Comment by breandan** [comment]
Merging with #327 / #310.
