### ISSUE TITLE
V. 3.7.0, line mode, not all tag options present

### ISSUE THREAD

**Issue by MichaelMedvedskiy** [acejump/AceJump#366]
**Describe the bug**
when using line mode, not all options are reflected, example in screenshots

1) screenshot of symbol sequence without tags
![image](https://user-images.githubusercontent.com/35178274/114942614-76ef5980-9e4d-11eb-9c3a-900ebe79162e.png)

2) Option to go behind **);** is missing
![image](https://user-images.githubusercontent.com/35178274/114942136-c3866500-9e4c-11eb-9abc-1359e76e525d.png)

3) after I go to **CF, BH** appears, **BH** places cursor after ); , which is what I want
*![image](https://user-images.githubusercontent.com/35178274/114942385-22e47500-9e4d-11eb-8768-22230421d93a.png)

**To Reproduce**
Have a "    );" sequence, try to acejump in normal mode

**Expected behavior**
Expected all 3 possible locations to go appear - start of the line - **VG**, before ); - **CF**, after ); - **BH**

**Comment by chylex** [comment]
There isn't enough space for the tags to appear on the screen, if you need precise control then I'd recommend using one of the 3 concrete modes (Line Starts / Indents / Ends) instead of Line Marks.

![obrazek](https://user-images.githubusercontent.com/3685160/117391800-0047f800-aef1-11eb-8492-bba10d7377c9.png)

**Comment by breandan** [comment]
@MichaelMedvedskiy Thanks for reporting. Possibly "works as intended", but let's merge this with #323, maybe we can improve tag placement in this scenario.
