### ISSUE TITLE
AceJump stops highlighting the correct line after adding new lines to the file

### ISSUE THREAD

**Issue by albrtbc** [acejump/AceJump#373]
**Describe the bug**
When you open a new file and use AceJump it works correctly. But if you add a new line and search again it seems like it doesn't refresh the document and highlights the words as if they were on a previous line, so it marks a line higher than it really is.

The more lines you add, the more the gap between the highlighting and the word you are looking for. In addition, everything new you add is not found.

**To Reproduce**
1. Open a file with text.
2. Add a new line at the top of the file
3. Search a word that's in the second line
4. Highlights the first line

**Expected behavior**
It should match the highlighted line with the current word.

**Screenshots**
Here I was searching for 'aaa' which is in the second line and it's highlighting the first line.
![image](https://user-images.githubusercontent.com/4415950/118155705-cf981f00-b418-11eb-8a9f-722f650df809.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE and version: Rider 2021.1.2
 - AceJump version: 3.8.0

**Additional context**
Looks like it caches the file and once you write new lines / stuff it doesn't refresh it so it's always looking for the old version line.

**Comment by breandan** [comment]
Hi @albrtbc, thank you for reporting this issue! I am a little surprised it slipped through undetected. Indeed, it was caused by a stale cache. I have added a test and confirmed the issue is no longer present as of [`3.8.1`](https://plugins.jetbrains.com/plugin/7086-acejump/versions/stable/119664). Please feel free to give it a try and report back should you encounter any other issues.

cc: @chylex Please have a look at [the fix](https://github.com/acejump/AceJump/commit/a169e3c751de05ec19e02cec0f3bd9de25a91490#diff-92ec1f61fed32cbbd6af051f8c4a73c0a238eee769f5f6439830ebdac4d684aaR21) and let me know if you have any questions or concerns.
