### ISSUE TITLE
Is it considered to make AceJump available in VSCode?

### ISSUE THREAD

**Issue by tufbel** [acejump/AceJump#412]
I think AceJump is the best of all the jump tools I've used so far.

**Comment by breandan** [comment]
Thank you for your feedback! It would be technically possible (since Kotlin compiles to JS/TS), however unless some willing volunteer wants to port AceJump to VSCode, we do not have any plans to support VSCode in the near future. In the mean time, you could try [Code Ace Jumper](https://marketplace.visualstudio.com/items?itemName=lucax88x.codeacejumper).
