### ISSUE TITLE
Sometimes can not jump to word in version 3.8.15

### ISSUE THREAD

**Issue by buptlibo** [acejump/AceJump#446]
**Describe the bug**
I don't even know how to describe or reproduce this bug consistently. Like the title, I don't know when it will occur.
eg: I want to jump to a word "List", after the shortcut 'ctrl-;', I enter key "L", like the image
![image](https://github.com/acejump/AceJump/assets/12469651/2a841c95-1771-4058-8dd5-337df4bb7977)
but at this time, when I enter 'J', nothing happened, however I can jump to the 'G' word.

**To Reproduce**
like the desc, I can not reproduce this bug consistently. It just 'sometimes'

**Expected behavior**
Can jump to any word.

**Desktop (please complete the following information):**
 - OS: mac os 11.7.1
 - IJ IDEA 2023.2.1
 - AceJump version 3.8.15

**Additional context**
In AceJump version 3.8.14, everything is ok(maybe), because I don't know under which circumstances this phenomenon will occur either.

**Comment by KienSetel** [comment]
It's happening to me as well. I just updated my Android Studio to Giraffe and this bug really annoys me. Just like @buptlibo the circumstances are not consistent. But can easily reproduce though.

**Comment by zhujiangzhou** [comment]
I have also encountered this problem recently.

- OS: Win10 22H2
- IDEA:  2023.2.1
- AceJump: 3.8.15

**Comment by shawnsong** [comment]
Having the same issue here.
- OS: macOS 13.5.2
- IDEA: 2023.2.1
- AceJump: 3.8.15

**Comment by luoxiao78** [comment]
same here, the inconsistency is very annoying. plz fix it. 

- OS: macOS 13.5.2
- IDEA: 2023.2.2
- AceJump: 3.8.15

**Comment by zxeoc** [comment]
same issue.

OS: Linux zx 6.4.12-arch1-1
IDEA: 2023.2.1
AceJump: 3.8.15

**Comment by breandan** [comment]
My bad! We recently tried to fix [an issue](#442) where users would accidentally jump to off-screen tags, but then introduced a regression where visible tags are occasionally classified as off-screen and thus unavailable to select. Since this bug is difficult to reproduce, I am not 100% sure if d905909e31c40d7ededd9f1a422c6592641d2a8c will fix the issue, but it is borrowed directly from the platform implementation of [`Editor.calculateVisibleRange()`](https://github.com/JetBrains/intellij-community/blob/b1737bbeb3db227a13a7301e1a2e4d84e8439d1b/platform/editor-ui-api/src/com/intellij/openapi/editor/Editor.java#L423-L431) so it should be more stable than the previous implementation. This should be available through an update from the plugin marketplace shortly. Please report back if you encounter this issue after upgrading to AceJump `3.8.16`. Thanks!

**Comment by buptlibo** [comment]
I think it works, thank you! @breandan

**Comment by KienSetel** [comment]
Thank you! @breandan , it works flawlessly for me so far!

**Comment by tanmaychimurkar** [comment]
Hi everyone, I had the same issue with `3.8.15`, and I can also confirm that this has been fixed with `3.8.16`!
