### ISSUE TITLE
kotlin-stdlib bundled in AceJump causes problems in Intellij Debugger

### ISSUE THREAD

**Issue by mvicsokolova** [acejump/AceJump#449]
Hi!
Recently we've run into the problem in IntelliJ Debugger that was caused by the conflict of several `kotlin-stdlib` versions found in the classpath of the project that uses AceJump plugin. I found that AceJump plugin bundles `kotlin-stdlib-*.jar` in its distributive (I've attached a screenshot of the unpacked zip of the latest AceJump plugin `3.8.16`). 

At some point IDEA platform will resolve this kind of problems automatically, but for now IDEA plugins should use `kotlin-stdlib` version provided by the IDEA platform and should not bundle `kotlin-stdlib` by themselves.

It would be great if you could exclude `kotlin-stdlib-*.jar` from the final AceJump distributive in the next release. 

<img width="326" alt="Bildschirmfoto 2023-10-27 um 18 14 41" src="https://github.com/acejump/AceJump/assets/82594708/6d8287c9-4283-4730-91cc-334904527e51">

**Comment by breandan** [comment]
Hi @mvicsokolova, thank you for reporting. If the [expectation](https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library) is for Kotlin IntelliJ Platform Plugins to avoid shipping the platform standard library, then I would have expected the flag `kotlin.stdlib.default.dependency` to be opt-in instead of opt-out by default. Originally we had the following line in our dependencies section, but it was removed after a certain point:

```
compileOnly(kotlin("stdlib"))
```

Happy to ship the #450, but from a plugin development standpoint, it seems like if conflicting standard libraries is a concern, then the `stdlib` dependency bundling should be overridden by [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin) (cc: @hsz), which seems more efficient that asking individual plugin authors to manually opt-out. Is there some technical reason this is not possible?

**Comment by chylex** [comment]
Agree the gradle plugin should set this by default, and also pick the correct minimum Kotlin version so developers don't need to reference the [table](https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library). The [plugin template](https://github.com/JetBrains/intellij-platform-plugin-template) sets both manually.

**Comment by mvicsokolova** [comment]
Thank you for such a quick unbundling!
I need to discuss what we can do to resolve the versions on the side of `gradle-intellij-plugin`, this seems very reasonable to me as well.

Can we expect this fix in the next AceJump release?

**Comment by hsz** [comment]
@breandan We don't apply this `kotlin.stdlib.default.dependency=false` to the project with Gradle IntelliJ Plugin by purpose.
By design, the project configuration is supposed to be immutable from the Gradle plugin perspective, and eventually, we "only" warn users about misconfiguration.
There's a dedicated [verifyPluginConfiguration](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/kotlin/org/jetbrains/intellij/tasks/VerifyPluginConfigurationTask.kt) task present, which analyzes your setup and prints warnings to the console output.

**Comment by chylex** [comment]
I've never heard of the `verifyPluginConfiguration` task and I have created or forked at least 15 IntelliJ plugins so far.

In my opinion, the Gradle plugin should have reasonable default behavior that will be relevant to 99% of people in the context of the project. Setting `kotlin.stdlib.default.dependency` to `false` by default makes sense when the project is an IntelliJ plugin.

I would expect that the Gradle plugin excludes the stdlib dependency unless I explicitly allow it, and I would also expect `buildPlugin` to depend on `verifyPluginConfiguration` and fail the build if the configuration is wrong. The verification task should have an option to not fail on a bundled stdlib, for the <1% who actually need it.

**Comment by hsz** [comment]
The `verifyPluginConfiguration` is run before any other task provided by the Gradle IntelliJ Plugin, including mentioned `buildPlugin`.
See an example build: https://github.com/JetBrains/intellij-platform-plugin-template/actions/runs/6441898534/job/17492163560

<img width="860" alt="image" src="https://github.com/acejump/AceJump/assets/108333/d0a8bcf2-9278-4d3b-8b53-53f11b3b9635">

For AceJump project it currently reports:
```
[gradle-intellij-plugin :verifyPluginConfiguration] The following plugin configuration issues were found:
- The 'since-build' property is lower than the target IntelliJ Platform major version: 223.7571.182 < 232.
See: https://jb.gg/intellij-platform-versions
```


But before the change you introduced with #450, it was already warning you about that particular problem:

```
> Task :verifyPluginConfiguration
[gradle-intellij-plugin :verifyPluginConfiguration] The following plugin configuration issues were found:
- The 'since-build' property is lower than the target IntelliJ Platform major version: 223.7571.182 < 232.
- The dependency on the Kotlin Standard Library (stdlib) is automatically added when using the Gradle Kotlin plugin and may conflict with the version provided with the IntelliJ Platform, see: https://jb.gg/intellij-platform-kotlin-stdlib
See: https://jb.gg/intellij-platform-versions
```

This task has been with us for over a year (introduced with version [1.9.0](https://github.com/JetBrains/gradle-intellij-plugin/releases/tag/v1.9.0)), so I believe such warnings are also present in other of your fifteen plugins - if misconfigured.

**Comment by breandan** [comment]
After thinking about this for a bit, I think @chylex is correct here, if Kotlin is a recommended language for plugin development and changes to the Kotlin compiler for some reason break the IDE, then it should be the responsibility of the Gradle plugin to either (1) unbundle the standard library and set the versioned `stdlib` sources to `compileOnly` for the targeted platform, or short of that, (2) fail the build.

Setting this particular issue aside, stability of the build script is important to ensuring a smooth plugin developer experience and requiring developers to periodically add obscure flags to configuration files detracts from that experience. We frequently update IntelliJ Gradle Plugin, but seldom compare the `intellij-platform-plugin-template` for new flags. In any case, I appreciate your communicating the issue with us.
